services:
  builder:
    privileged: true
    tty: true
    hostname: builder
    container_name: builder
    image: ghcr.io/stepherg/dev/builder:latest
    volumes:
      - ~/projects/rdkb:/home/stepherg/projects/rdkb
      - ~/bin:/home/stepherg/bin:Z
      - ~/.netrc:/home/stepherg/.netrc:ro
      - ~/.git-credentials:/home/stepherg/.git-credentials:ro
      - ~/.gitconfig:/home/stepherg/.gitconfig:ro
      - ./configs/builder/ssh:/home/stepherg/.ssh:ro

    ports:
      - "2225:22"
