services:
  bpivcpe:
    privileged: true
    tty: true
    hostname: bpivcpe
    container_name: bpivcpe
    image: ghcr.io/stepherg/vcpe/bpi:latest
    networks:
      - vcpe

networks:
  vcpe:
    external: true
