services:
  bpisdk:
    privileged: true
    tty: true
    hostname: bpisdk
    container_name: bpisdk
    image: bpisdk:latest
    network_mode: host
    volumes:
      - "~/projects/rdkb:/home/stepherg/projects/rdkb"
      - "~/bin:/home/stepherg/bin:Z"
      - "~/.netrc:/home/stepherg/.netrc:ro"
      - ./configs/builder/gitconfig:/home/stepherg/.gitconfig:ro
      - ./configs/builder/ssh:/home/stepherg/.ssh:ro
      - "~/.git-credentials:/home/stepherg/.git-credentials:ro"

    #ports:
    #  - "2225:22"
