services:
  bpidev:
    privileged: true
    tty: true
    hostname: bpidev
    container_name: bpidev
    image: ghcr.io/stepherg/dev/bpi:latest
    networks:
      - vcpe

networks:
  vcpe:
    external: true
