FROM bpi-dev:latest

ARG TARGET_ARCH=cortexa53

RUN mkdir -p /nvram/secure
RUN systemctl disable dnsmasq.service \
   && systemctl disable RdkTelcoVoiceManager.service \
   && systemctl disable miniupnpd.service

ENV SDKTARGETSYSROOT=/
ENV TARGET_ARCH=${TARGET_ARCH}

RUN echo 'PS1="[\u@${TARGET_ARCH}-sdk \W]\\$ "' >> /home/root/.bashrc

RUN echo "src/gz custom-packages https://stepherg.github.io/package-workflows/opkg" | tee -a /etc/opkg/customfeeds.conf \
   && opkg update

CMD ["/sbin/init"]
