FROM ubuntu:20.04

ARG USER_NAME=stepherg
ARG USER_ID=502
ARG GROUP_ID=502

RUN groupadd -g ${GROUP_ID} ${USER_NAME}
RUN useradd -m -u ${USER_ID} -g ${GROUP_ID} -s /usr/bin/bash ${USER_NAME}
RUN passwd -d root
RUN mkdir -p /home/${USER_NAME}/.ssh
COPY ./dev/${USER_NAME} /etc/sudoers.d/${USER_NAME}
COPY --chmod=600 ./configs/builder/ssh/* /root/.ssh/
COPY --chmod=600 ./configs/builder/ssh/* /home/${USER_NAME}/.ssh/
COPY --chmod=644 ./configs/builder/gitconfig /home/${USER_NAME}/.gitconfig
RUN echo 'PS1="[\u@\h \W]\\$ "' >> /home/${USER_NAME}/.bashrc
RUN echo 'PS1="[\u@\h \W]\\$ "' >> /root/.bashrc
RUN echo "" >> /home/${USER_NAME}/.bashrc
RUN echo "" >> /root/.bashrc

RUN chown root:root /etc/sudoers.d/${USER_NAME}
RUN chown -R ${USER_NAME}:${USER_NAME} /home/${USER_NAME}

ENV TZ=America/New_York \
    DEBIAN_FRONTEND=noninteractive

RUN apt-get update

RUN apt-get -y upgrade

RUN apt-get -y install \
    build-essential \
    gcc \
    g++ \
    clang \
    cmake \
    rsync \
    tar \
    python3 \
    ninja-build \
    dos2unix \
    systemd-sysv \
    gdb \
    gdb-multiarch \
    openssh-server \
    sudo \
    curl \
    git \
    vim \
    net-tools \
    dnsutils \
    iputils-ping \
    iputils-tracepath \
    libssl-dev \
    libcurl4-openssl-dev\
    libsqlite3-dev \
    libz-dev \
    autoconf \
    automake \
    libtool \
    libmosquitto-dev \
    libwebsockets-dev \
    pkg-config \
    make \
    cmake \
    vim \
    git \
    wget \
    dnsutils \
    iputils-ping \
    iputils-tracepath \
    python3-pip \
    jq \
    flake8 \
    tmux \
    black \
    python3-venv \
    bison \
    libcjson-dev \
    sshfs \
    lua5.1 liblua5.1-0-dev libjson-c-dev \
    gawk wget python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev pylint3 xterm python3-subunit mesa-common-dev zstd liblz4-tool git diffstat unzip texinfo gcc build-essential chrpath socat cpio python python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping make xsltproc docbook-utils fop dblatex xmlto curl locales vim git-extras tree valgrind exuberant-ctags cscope dos2unix lcov libcunit1-dev libjson-perl members screen silversearcher-ag git-review nano

RUN locale-gen en_US.UTF-8

# Set-up SSH for remote debug
EXPOSE 22/tcp
RUN service ssh start
CMD ["/sbin/init"]




